### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by Raudience** [CUC-Life-Hack/rainclass-hack#1]
https://github.com/CUC-Life-Hack/rainclass-hack/blob/master/dist/main.user.js
脚本不能运行，（可能是脚本作用域网址不对？）

**Comment by WangNianyi2001** [comment]
应该就是 URL 匹配的问题。上个月在搞另一个 hack 的时候调查发现 userscript 在匹配时会截断 URL 中 search params 的部分。
我 build 了一个[临时开发版本](https://github.com/CUC-Life-Hack/rainclass-hack/blob/master/dev/main.user.js)，你试试看这个能不能用？
