### ISSUE TITLE
release版本可以显示面板但无效，dev版本不显示面板

### ISSUE THREAD

**Issue by greenredstone** [CUC-Life-Hack/rainclass-hack#2]
release版本点击“自动”按钮时会自行定位到有视频的课件页，但是并不会观看视频，其余按钮完全无效。dev版本在油猴管理器内正常显示，但是网页内没有显示

**Comment by WangNianyi2001** [comment]
Sorry for late reply. 本学期课业略忙，建议加 QQ 群（见组织主页）反馈。我会抽空修 bug。

**Comment by WangNianyi2001** [comment]
Closed in [0b7ca4](https://github.com/CUC-Life-Hack/rainclass-hack/commit/0b7ca46d4386e4dcb5d5e75d2ae17c3bde5ce523).
